// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8080' | (string & {});
};

export type ErrorResponse = {
    status?: number;
    message?: string;
    path?: string;
    errors?: {
        [key: string]: string;
    };
    timestamp?: string;
};

export type ReviewRequest = {
    rating?: number;
    text?: string;
};

export type ReviewDto = {
    id?: string;
    listingId?: string;
    author?: UserDto;
    rating?: number;
    text?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type UserDto = {
    id?: string;
    username?: string;
    email?: string;
    role?: 'admin' | 'user';
    verified?: 'none' | 'pending' | 'verified' | 'rejected';
    createdAt?: string;
    blocked?: boolean;
    verificationReason?: string;
    blockReason?: string;
};

export type ListingForm = {
    title?: string;
    description?: string;
    city?: string;
    address?: string;
    price: number;
    maxGuests: number;
    type?: string;
    status?: string;
    imageUrls?: Array<string>;
    images?: Array<Blob | File>;
};

export type ListingDto = {
    id?: string;
    title?: string;
    description?: string;
    city?: string;
    address?: string;
    price?: number;
    maxGuests?: number;
    images?: Array<string>;
    rating?: number;
    type?: 'apartment' | 'house' | 'room';
    isOwner?: boolean;
    ownerUsername?: string;
    status?: 'review' | 'active' | 'blocked';
};

export type UploadResponse = {
    urls?: Array<string>;
};

export type BookingRequest = {
    startDate: string;
    endDate: string;
};

export type BookingDto = {
    id?: string;
    listingId?: string;
    listing?: ListingDto;
    userId?: string;
    user?: UserDto;
    startDate?: string;
    endDate?: string;
    pricePerDay?: number;
    totalPrice?: number;
    status?: 'active' | 'cancelled' | 'provided';
    createdAt?: string;
    updatedAt?: string;
};

export type FavoriteRequest = {
    listingId: string;
};

export type FavoriteMergeRequest = {
    listingIds?: Array<string>;
};

export type VerifyEmailRequest = {
    code?: string;
};

export type AuthResponse = {
    user?: UserDto;
    accessToken?: string;
};

export type RegisterRequest = {
    username?: string;
    email?: string;
    password?: string;
    repeatPassword?: string;
    captcha?: string;
};

export type MessageResponse = {
    message?: string;
};

export type LoginRequest = {
    email?: string;
    password?: string;
    captcha?: string;
};

export type PasswordChangeRequest = {
    oldPassword?: string;
    password?: string;
    passwordRepeat?: string;
};

export type NotificationDto = {
    id?: string;
    userId?: string;
    type?: 'booking_created' | 'booking_cancelled' | 'booking_period_changed' | 'review_updated' | 'user_verified' | 'user_verification_rejected' | 'user_blocked' | 'user_unblocked' | 'listing_approved' | 'listing_rejected';
    title?: string;
    text?: string;
    link?: string;
    isRead?: boolean;
    createdAt?: string;
};

export type AdminUserDto = {
    id?: string;
    username?: string;
    email?: string;
    role?: 'admin' | 'user';
    verified?: 'none' | 'pending' | 'verified' | 'rejected';
    createdAt?: string;
    blocked?: boolean;
    verificationReason?: string;
    blockReason?: string;
    documents?: Array<string>;
};

export type ReasonRequest = {
    reason?: string;
};

export type ProfileStatsDto = {
    bookings?: number;
    listings?: number;
    favorites?: number;
    reviews?: number;
};

export type PageResponseListingDto = {
    items?: Array<ListingDto>;
    page?: number;
    limit?: number;
    total?: number;
};

export type UpdateReviewData = {
    body: ReviewRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/reviews/{id}';
};

export type UpdateReviewErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UpdateReviewError = UpdateReviewErrors[keyof UpdateReviewErrors];

export type UpdateReviewResponses = {
    /**
     * OK
     */
    200: ReviewDto;
};

export type UpdateReviewResponse = UpdateReviewResponses[keyof UpdateReviewResponses];

export type DeleteListingData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/listings/{id}';
};

export type DeleteListingErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type DeleteListingError = DeleteListingErrors[keyof DeleteListingErrors];

export type DeleteListingResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteListingResponse = DeleteListingResponses[keyof DeleteListingResponses];

export type GetListingByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/listings/{id}';
};

export type GetListingByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetListingByIdError = GetListingByIdErrors[keyof GetListingByIdErrors];

export type GetListingByIdResponses = {
    /**
     * OK
     */
    200: ListingDto;
};

export type GetListingByIdResponse = GetListingByIdResponses[keyof GetListingByIdResponses];

export type UpdateListingData = {
    body?: ListingForm;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/listings/{id}';
};

export type UpdateListingErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UpdateListingError = UpdateListingErrors[keyof UpdateListingErrors];

export type UpdateListingResponses = {
    /**
     * OK
     */
    200: ListingDto;
};

export type UpdateListingResponse = UpdateListingResponses[keyof UpdateListingResponses];

export type UploadDocumentsData = {
    body?: {
        files: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/api/users/me/documents';
};

export type UploadDocumentsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UploadDocumentsError = UploadDocumentsErrors[keyof UploadDocumentsErrors];

export type UploadDocumentsResponses = {
    /**
     * OK
     */
    200: UploadResponse;
};

export type UploadDocumentsResponse = UploadDocumentsResponses[keyof UploadDocumentsResponses];

export type UploadImagesData = {
    body?: {
        files: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/api/uploads/images';
};

export type UploadImagesErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UploadImagesError = UploadImagesErrors[keyof UploadImagesErrors];

export type UploadImagesResponses = {
    /**
     * OK
     */
    200: UploadResponse;
};

export type UploadImagesResponse = UploadImagesResponses[keyof UploadImagesResponses];

export type GetListingsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        sortBy?: string;
        order?: string;
        city?: string;
        priceFrom?: number;
        priceTo?: number;
        minGuests?: number;
        ratingFrom?: number;
        ratingTo?: number;
        category?: string;
    };
    url: '/api/listings';
};

export type GetListingsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetListingsError = GetListingsErrors[keyof GetListingsErrors];

export type GetListingsResponses = {
    /**
     * OK
     */
    200: PageResponseListingDto;
};

export type GetListingsResponse = GetListingsResponses[keyof GetListingsResponses];

export type CreateListingData = {
    body?: ListingForm;
    path?: never;
    query?: never;
    url: '/api/listings';
};

export type CreateListingErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type CreateListingError = CreateListingErrors[keyof CreateListingErrors];

export type CreateListingResponses = {
    /**
     * Created
     */
    201: ListingDto;
};

export type CreateListingResponse = CreateListingResponses[keyof CreateListingResponses];

export type GetListingReviewsData = {
    body?: never;
    path: {
        listingId: string;
    };
    query?: never;
    url: '/api/listings/{listingId}/reviews';
};

export type GetListingReviewsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetListingReviewsError = GetListingReviewsErrors[keyof GetListingReviewsErrors];

export type GetListingReviewsResponses = {
    /**
     * OK
     */
    200: Array<ReviewDto>;
};

export type GetListingReviewsResponse = GetListingReviewsResponses[keyof GetListingReviewsResponses];

export type CreateReviewData = {
    body: ReviewRequest;
    path: {
        listingId: string;
    };
    query?: never;
    url: '/api/listings/{listingId}/reviews';
};

export type CreateReviewErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type CreateReviewError = CreateReviewErrors[keyof CreateReviewErrors];

export type CreateReviewResponses = {
    /**
     * Created
     */
    201: ReviewDto;
};

export type CreateReviewResponse = CreateReviewResponses[keyof CreateReviewResponses];

export type GetListingBookingsData = {
    body?: never;
    path: {
        listingId: string;
    };
    query?: never;
    url: '/api/listings/{listingId}/bookings';
};

export type GetListingBookingsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetListingBookingsError = GetListingBookingsErrors[keyof GetListingBookingsErrors];

export type GetListingBookingsResponses = {
    /**
     * OK
     */
    200: Array<BookingDto>;
};

export type GetListingBookingsResponse = GetListingBookingsResponses[keyof GetListingBookingsResponses];

export type CreateBookingData = {
    body: BookingRequest;
    path: {
        listingId: string;
    };
    query?: never;
    url: '/api/listings/{listingId}/bookings';
};

export type CreateBookingErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type CreateBookingError = CreateBookingErrors[keyof CreateBookingErrors];

export type CreateBookingResponses = {
    /**
     * OK
     */
    200: BookingDto;
};

export type CreateBookingResponse = CreateBookingResponses[keyof CreateBookingResponses];

export type GetListingsByIdsData = {
    body: Array<string>;
    path?: never;
    query?: never;
    url: '/api/listings/batch';
};

export type GetListingsByIdsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetListingsByIdsError = GetListingsByIdsErrors[keyof GetListingsByIdsErrors];

export type GetListingsByIdsResponses = {
    /**
     * OK
     */
    200: Array<ListingDto>;
};

export type GetListingsByIdsResponse = GetListingsByIdsResponses[keyof GetListingsByIdsResponses];

export type GetMyFavoritesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/favorites';
};

export type GetMyFavoritesErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetMyFavoritesError = GetMyFavoritesErrors[keyof GetMyFavoritesErrors];

export type GetMyFavoritesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetMyFavoritesResponse = GetMyFavoritesResponses[keyof GetMyFavoritesResponses];

export type AddFavoriteData = {
    body: FavoriteRequest;
    path?: never;
    query?: never;
    url: '/api/favorites';
};

export type AddFavoriteErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type AddFavoriteError = AddFavoriteErrors[keyof AddFavoriteErrors];

export type AddFavoriteResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type AddFavoriteResponse = AddFavoriteResponses[keyof AddFavoriteResponses];

export type MergeFavoritesData = {
    body: FavoriteMergeRequest;
    path?: never;
    query?: never;
    url: '/api/favorites/merge';
};

export type MergeFavoritesErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type MergeFavoritesError = MergeFavoritesErrors[keyof MergeFavoritesErrors];

export type MergeFavoritesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type MergeFavoritesResponse = MergeFavoritesResponses[keyof MergeFavoritesResponses];

export type VerifyEmailData = {
    body: VerifyEmailRequest;
    path?: never;
    query?: never;
    url: '/api/auth/verify-email';
};

export type VerifyEmailErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type VerifyEmailError = VerifyEmailErrors[keyof VerifyEmailErrors];

export type VerifyEmailResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type VerifyEmailResponse = VerifyEmailResponses[keyof VerifyEmailResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Created
     */
    201: MessageResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type RefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshTokenErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type ChangePasswordData = {
    body: PasswordChangeRequest;
    path?: never;
    query?: never;
    url: '/api/users/me/password';
};

export type ChangePasswordErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type MarkNotificationAsReadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/notifications/{id}/read';
};

export type MarkNotificationAsReadErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type MarkNotificationAsReadError = MarkNotificationAsReadErrors[keyof MarkNotificationAsReadErrors];

export type MarkNotificationAsReadResponses = {
    /**
     * OK
     */
    200: NotificationDto;
};

export type MarkNotificationAsReadResponse = MarkNotificationAsReadResponses[keyof MarkNotificationAsReadResponses];

export type MarkAllNotificationsAsReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications/read-all';
};

export type MarkAllNotificationsAsReadErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type MarkAllNotificationsAsReadError = MarkAllNotificationsAsReadErrors[keyof MarkAllNotificationsAsReadErrors];

export type MarkAllNotificationsAsReadResponses = {
    /**
     * No Content
     */
    204: void;
};

export type MarkAllNotificationsAsReadResponse = MarkAllNotificationsAsReadResponses[keyof MarkAllNotificationsAsReadResponses];

export type ChangeBookingPeriodData = {
    body: BookingRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/bookings/{id}/period';
};

export type ChangeBookingPeriodErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ChangeBookingPeriodError = ChangeBookingPeriodErrors[keyof ChangeBookingPeriodErrors];

export type ChangeBookingPeriodResponses = {
    /**
     * OK
     */
    200: BookingDto;
};

export type ChangeBookingPeriodResponse = ChangeBookingPeriodResponses[keyof ChangeBookingPeriodResponses];

export type CancelBookingData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/bookings/{id}/cancel';
};

export type CancelBookingErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type CancelBookingError = CancelBookingErrors[keyof CancelBookingErrors];

export type CancelBookingResponses = {
    /**
     * OK
     */
    200: BookingDto;
};

export type CancelBookingResponse = CancelBookingResponses[keyof CancelBookingResponses];

export type VerifyUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/users/{id}/verify';
};

export type VerifyUserErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type VerifyUserError = VerifyUserErrors[keyof VerifyUserErrors];

export type VerifyUserResponses = {
    /**
     * OK
     */
    200: AdminUserDto;
};

export type VerifyUserResponse = VerifyUserResponses[keyof VerifyUserResponses];

export type UnblockUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/users/{id}/unblock';
};

export type UnblockUserErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UnblockUserError = UnblockUserErrors[keyof UnblockUserErrors];

export type UnblockUserResponses = {
    /**
     * OK
     */
    200: AdminUserDto;
};

export type UnblockUserResponse = UnblockUserResponses[keyof UnblockUserResponses];

export type RejectUserVerificationData = {
    body: ReasonRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/users/{id}/reject-verification';
};

export type RejectUserVerificationErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type RejectUserVerificationError = RejectUserVerificationErrors[keyof RejectUserVerificationErrors];

export type RejectUserVerificationResponses = {
    /**
     * OK
     */
    200: AdminUserDto;
};

export type RejectUserVerificationResponse = RejectUserVerificationResponses[keyof RejectUserVerificationResponses];

export type BlockUserData = {
    body: ReasonRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/users/{id}/block';
};

export type BlockUserErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type BlockUserError = BlockUserErrors[keyof BlockUserErrors];

export type BlockUserResponses = {
    /**
     * OK
     */
    200: AdminUserDto;
};

export type BlockUserResponse = BlockUserResponses[keyof BlockUserResponses];

export type RejectListingData = {
    body: ReasonRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/listings/{id}/reject';
};

export type RejectListingErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type RejectListingError = RejectListingErrors[keyof RejectListingErrors];

export type RejectListingResponses = {
    /**
     * OK
     */
    200: ListingDto;
};

export type RejectListingResponse = RejectListingResponses[keyof RejectListingResponses];

export type ApproveListingData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/listings/{id}/approve';
};

export type ApproveListingErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ApproveListingError = ApproveListingErrors[keyof ApproveListingErrors];

export type ApproveListingResponses = {
    /**
     * OK
     */
    200: ListingDto;
};

export type ApproveListingResponse = ApproveListingResponses[keyof ApproveListingResponses];

export type GetMyStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profile/stats';
};

export type GetMyStatsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetMyStatsError = GetMyStatsErrors[keyof GetMyStatsErrors];

export type GetMyStatsResponses = {
    /**
     * OK
     */
    200: ProfileStatsDto;
};

export type GetMyStatsResponse = GetMyStatsResponses[keyof GetMyStatsResponses];

export type GetMyNotificationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications';
};

export type GetMyNotificationsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetMyNotificationsError = GetMyNotificationsErrors[keyof GetMyNotificationsErrors];

export type GetMyNotificationsResponses = {
    /**
     * OK
     */
    200: Array<NotificationDto>;
};

export type GetMyNotificationsResponse = GetMyNotificationsResponses[keyof GetMyNotificationsResponses];

export type GetMyListingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/listings/my';
};

export type GetMyListingsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetMyListingsError = GetMyListingsErrors[keyof GetMyListingsErrors];

export type GetMyListingsResponses = {
    /**
     * OK
     */
    200: Array<ListingDto>;
};

export type GetMyListingsResponse = GetMyListingsResponses[keyof GetMyListingsResponses];

export type GetMyFavoriteListingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/favorites/listings';
};

export type GetMyFavoriteListingsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetMyFavoriteListingsError = GetMyFavoriteListingsErrors[keyof GetMyFavoriteListingsErrors];

export type GetMyFavoriteListingsResponses = {
    /**
     * OK
     */
    200: Array<ListingDto>;
};

export type GetMyFavoriteListingsResponse = GetMyFavoriteListingsResponses[keyof GetMyFavoriteListingsResponses];

export type GetMyBookingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bookings/my';
};

export type GetMyBookingsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetMyBookingsError = GetMyBookingsErrors[keyof GetMyBookingsErrors];

export type GetMyBookingsResponses = {
    /**
     * OK
     */
    200: Array<BookingDto>;
};

export type GetMyBookingsResponse = GetMyBookingsResponses[keyof GetMyBookingsResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetMeErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type GetAdminUsersData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        verificationFilter?: string;
        sortOrder?: string;
    };
    url: '/api/admin/users';
};

export type GetAdminUsersErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetAdminUsersError = GetAdminUsersErrors[keyof GetAdminUsersErrors];

export type GetAdminUsersResponses = {
    /**
     * OK
     */
    200: Array<AdminUserDto>;
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type GetReviewListingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/listings/review';
};

export type GetReviewListingsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetReviewListingsError = GetReviewListingsErrors[keyof GetReviewListingsErrors];

export type GetReviewListingsResponses = {
    /**
     * OK
     */
    200: Array<ListingDto>;
};

export type GetReviewListingsResponse = GetReviewListingsResponses[keyof GetReviewListingsResponses];

export type RemoveFavoriteData = {
    body?: never;
    path: {
        listingId: string;
    };
    query?: never;
    url: '/api/favorites/{listingId}';
};

export type RemoveFavoriteErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type RemoveFavoriteError = RemoveFavoriteErrors[keyof RemoveFavoriteErrors];

export type RemoveFavoriteResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type RemoveFavoriteResponse = RemoveFavoriteResponses[keyof RemoveFavoriteResponses];
